name: Build Porytiles Clang
on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
jobs:
  build-ubuntu-clang-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Ubuntu Clang
        run: |
          sudo apt-get install zlib1g-dev
          sudo apt-get install libpng-dev
          clang++ --version
          CXX=clang++ make
          CXX=clang++ make check
  build-ubuntu-clang-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Ubuntu Clang
        run: |
          sudo apt-get install zlib1g-dev
          sudo apt-get install libpng-dev
          clang++ --version
          CXX=clang++ make debug
          CXX=clang++ make debug-check

#  build-mac-clang:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Build Mac Clang
#        run: |
#          brew update
#          brew install zlib
#          brew install libpng
#          brew upgrade
#          make