name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install zlib
      run: sudo apt-get install zlib1g-dev
    - name: Install LibPNG
      run: sudo apt-get install libpng-dev
    - name: Build Porymoves
      run: make
